<?php

namespace Test\UserBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    function getByNameWithArticles($name)
    {
        $qb = $this->createQueryBuilder('u');
        $query = $qb->leftJoin('u.articles','a')
            ->where($qb->expr()->in('u.username',$name))
            ->addSelect('a')
            ->OrderBy('a.date','DESC')
            ->getQuery();

        return $query->getResult();
    }
}
