<?php

namespace Test\MainBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MainController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Test\MainBundle\Controller\MainController();
        return $instance;
    }
}
