<?php

namespace Test\BlogBundle\Entity;

/**
 * ArticleCompetenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleCompetenceRepository extends \Doctrine\ORM\EntityRepository
{

}
