<?php

namespace Test\BlogBundle\Entity;

/**
 * CategoryHolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryHolderRepository extends \Doctrine\ORM\EntityRepository
{
}
